#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo -e "Script must be run as root. Try 'sudo ./$o'\n"
	exit 1
fi

apt-get update
apt-get -y autoclean
apt-get -y -f dist-upgrade
while (( "$#")); do
    apt-get -y install $1
    shift    
done
apt-get -y autoremove

