#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo -e "Script must be run as root. Try 'sudo ./$0'\n"
	exit 1
fi
    
if [ -f "/etc/icinga/icinga.cfg" ]; then
	/usr/sbin/icinga -v /etc/icinga/icinga.cfg
fi

if [ -f "/etc/icinga2/icinga2.conf" ]; then
	icinga2 daemon -C
fi
