#!/bin/bash

if [ $(id -u) -ne 0 ]; then
	echo -e "Script must be run as root. Try 'sudo $0'\n"
	exit 1
fi
    
if [ -f "/etc/icinga/icinga.cfg" ]; then
	service icinga restart
fi

if [ -f "/etc/icinga2/icinga2.conf" ]; then
	service icinga2 restart
fi


